// This file was generated by ts-rs. Do not edit this file manually.

export type HealthResponse = { status: string, };

export type AuthResponse = { ok: boolean, };

export type SessionInfo = { id: string, user_agent: string | null, ip: string | null, created_at: number, last_seen_at: number, expires_at: number, current: boolean, };

export type ApiModel = { id: string, name: string, context_length: number, pricing: ModelPricing, input_modalities: Array<string>, };

export type ModelPricing = { prompt: string, completion: string, };

export type ModelsResponse = { items: Array<ApiModel>, };

export type OpenRouterKeyStatus = { set: boolean, hint: string | null, valid: boolean, readable: boolean, };

export type UploadLimits = { image_bytes: number, pdf_bytes: number, text_bytes: number, files_per_message: number, total_prompt_bytes: number, };

export type SettingsResponse = { openrouter_api_key: OpenRouterKeyStatus, default_model: string | null, title_model: string | null, favorite_models: Array<string>, custom_instructions: string, pdf_engine: string, upload_limits: UploadLimits, };

export type ChatSummary = { id: string, title: string | null, model: string, updated_at: number, };

export type ChatPage = { items: Array<ChatSummary>, next_cursor: string | null, };

export type ChatDetail = { id: string, title: string | null, title_source: string, model: string, current_leaf_id: string | null, created_at: number, updated_at: number, messages: Array<MessageRecord>, };

export type SearchResult = { chat_id: string, chat_title: string | null, message_id: string | null, snippet: string, rank: number, };

export type SwitchBranchResponse = { current_leaf_id: string, };

export type MessageRecord = { id: string, chat_id: string, parent_id: string | null, role: string, content: string, status: string, error: string | null, model: string | null, generation_id: string | null, finish_reason: string | null, prompt_tokens: number | null, completion_tokens: number | null, reasoning_tokens: number | null, cost: number | null, created_at: number, updated_at: number, attachments: Array<MessageAttachment>, };

export type MessageAttachment = { upload_id: string, position: number, pdf_engine: string | null, parse_cache: string | null, };

export type SendMessageResponse = { user_message: MessageRecord, assistant_message: MessageRecord, };

export type NewChatMessageResponse = { chat: ChatSummary, user_message: MessageRecord, assistant_message: MessageRecord, };

export type RegenerateMessageResponse = { assistant_message: MessageRecord, };
