// This file was generated by ts-rs. Do not edit this file manually.

export type HealthResponse = { status: string, };

export type AuthResponse = { ok: boolean, };

export type SessionInfo = { id: string, user_agent: string | null, ip: string | null, created_at: number, last_seen_at: number, expires_at: number, current: boolean, };
