use serde::Serialize;
use std::{error::Error, fs, path::PathBuf};
use ts_rs::TS;

#[derive(Debug, Serialize, TS)]
pub struct HealthResponse {
    pub status: String,
}

#[derive(Debug, Serialize, TS)]
pub struct AuthResponse {
    pub ok: bool,
}

#[derive(Debug, Serialize, TS)]
pub struct SessionInfo {
    pub id: String,
    pub user_agent: Option<String>,
    pub ip: Option<String>,
    #[ts(type = "number")]
    pub created_at: i64,
    #[ts(type = "number")]
    pub last_seen_at: i64,
    #[ts(type = "number")]
    pub expires_at: i64,
    pub current: bool,
}

pub fn export() -> Result<(), Box<dyn Error>> {
    let target = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../web/src/api/types.gen.ts");
    if let Some(parent) = target.parent() {
        fs::create_dir_all(parent)?;
    }
    let declarations = [
        format!("export type HealthResponse = {};", HealthResponse::inline()),
        format!("export type AuthResponse = {};", AuthResponse::inline()),
        format!("export type SessionInfo = {};", SessionInfo::inline()),
    ];
    let contents = format!(
        "// This file was generated by ts-rs. Do not edit this file manually.\n\n{}\n",
        declarations.join("\n\n")
    );
    fs::write(&target, contents)?;
    println!("Wrote {}", target.display());
    Ok(())
}
